name: Lint and test with coverage

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  debug-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: npm
      - name: Install dependencies and run tests
        run: |
          npm ci
          npm run build
      - name: Save index.html to artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: index
          path: _site/index.html
          retention-days: 5
  lint-and-test-with-coverage:
    uses: inclusive-design/workflows/.github/workflows/node-lint-and-test-with-coverage.yml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
